kind: FreeFlowPolicySequence
apiVersion: api.ibm.com/v1
metadata:
  name: singapore-air-temperature-sequence
  version: '1.0'
  namespace: BYOCA-demo
  tags:
    - environment
    - singapore
spec:
  monitoring:
    $ref: BYOCA-demo:singapore-air-temperature-telemetry:1.0
  main:
    - $ref: BYOCA-demo:singapore-air-temperature-extract-identity:1.0
    - $ref: BYOCA-demo:singapore-air-temperature-authenticate:1.0
    - $ref: BYOCA-demo:singapore-air-temperature-authorize:1.0
    - $ref: BYOCA-demo:singapore-air-temperature-invoke:1.0
