kind: API
apiVersion: api.ibm.com/v1
metadata:
  name: air-temperature-api
  version: '1'
  namespace: air-temperature-demo
  description: Singapore Air Temperature API — NEA real-time weather data
  tags:
    - environment
    - weather
spec:
  api-spec:
    $path: ../spec/air-temperature-api-openapi.yaml
  uriSchemes:
    $ref: 'air-temperature-demo:air-temperature-api-uri-schemes:1'
  policy-sequence:
    - $ref: 'air-temperature-demo:air-temperature-api-sequence:1'
