kind: ExtractIdentity
apiVersion: api.ibm.com/v1
metadata:
  name: singapore-air-temperature-extract-identity
  version: '1'
  namespace: singapore-air-temperature
  tags:
    - environment
    - weather
spec:
  credentialType:
    apiKey:
      clientId:
        httpHeader:
          name: X-IBM-Client-Id
      clientSecret:
        httpHeader:
          name: X-IBM-Client-Secret
