kind: Authorize
apiVersion: api.ibm.com/v1
metadata:
  name: singapore-air-temperature-authorize
  version: '1.0'
  namespace: BYOCA-demo
  tags:
    - environment
    - singapore
spec:
  operation:
    subscription: {}
