kind: URISchemes
apiVersion: api.ibm.com/v1
metadata:
  name: air-temperature-api-uri-schemes
  version: '1'
  namespace: air-temperature-demo
  tags:
    - environment
    - weather
spec:
  uriSchemes:
    - https
