kind: Quota
apiVersion: api.ibm.com/v1
metadata:
  name: project-demo-quota-x7k2p
  namespace: project-demo
  version: 1
  tags: []
spec:
  maxRequest: 1000
  interval: 1m
  extensions:
    dp-nano-gateway:
      apiVersion: api.ibm.com/v1
      spec:
        exceedAction: return429
