kind: Invoke
apiVersion: api.ibm.com/v1
metadata:
  name: singapore-air-temperature-invoke
  namespace: singapore-air-temperature
  version: '1'
  tags:
    - environment
    - weather
spec:
  endpoint:
    http:
      target:
        url: >-
          'https://sample-api.eu-west-a.apiconnect.automation.ibm.com/environment'
          & $relativeUrl('request')
        urlType: jsonata
        timeout: 60
        version: HTTP/1.1
        tlsClientProfile: tls-client-profile-default:1.0.0
