kind: API
apiVersion: api.ibm.com/v1
metadata:
  name: singapore-air-temperature
  version: '1'
  namespace: demo
  tags:
    - environment
    - singapore
spec:
  api-spec:
    $path: ../spec/singapore-air-temperature-openapi.yaml
  uriSchemes:
    $ref: demo:singapore-air-temperature-uri-schemes:1
  policy-sequence:
    - $ref: demo:singapore-air-temperature-sequence:1
