kind: Telemetry
apiVersion: api.ibm.com/v1
metadata:
  name: singapore-air-temperature-telemetry
  version: '1'
  namespace: demo
  tags:
    - environment
    - singapore
spec:
  verbosity:
    - level: normal
