kind: Quota
apiVersion: api.ibm.com/v1
metadata:
  name: air-temperature-mcp-quota-k7m2p
  namespace: air-temperature-mcp
  version: '1'
  tags: []
spec:
  maxRequest: 1000
  interval: 1m
  extensions:
    dp-nano-gateway:
      apiVersion: api.ibm.com/v1
      spec:
        exceedAction: return429
