kind: FreeFlowPolicySequence
apiVersion: api.ibm.com/v1
metadata:
  name: air-temperature-mcp-freeflowpolicysequence-k7m2p
  namespace: air-temperature-mcp
  version: '1'
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  main:
    - $ref: air-temperature-mcp:invoke-k7m2p:1
  monitoring:
    $ref: air-temperature-mcp:telemetry-k7m2p:1
