kind: Invoke
apiVersion: api.ibm.com/v1
metadata:
  name: invoke-k7m2p
  namespace: air-temperature-mcp
  version: '1'
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  endpoint:
    http:
      target:
        tlsClientProfile: tls-client-profile-default:1.0.0
        url: "'https://sample-api.eu-west-a.apiconnect.automation.ibm.com/environment/air-temperature' & $pathAndQuery()"
        urlType: jsonata
        persistentConnections: false
        timeout: 30
        decompressResponse: true
        followRedirects: false
        chunkedUpload: false
