kind: MCPServer
apiVersion: api.ibm.com/v1
metadata:
  name: singapore-air-temperature-api-mcp-server-k7m2p
  namespace: air-temperature-mcp
  version: '1'
  tags: []
spec:
  title: Singapore Air Temperature API MCP Server
  protocolVersion: V2025_11_25
  policy-sequence:
    - $ref: air-temperature-mcp:air-temperature-mcp-freeflowpolicysequence-k7m2p:1
  capabilities:
    tools:
      - $ref: air-temperature-mcp:singapore-air-temperature-api-mcp-tool-k7m2p:1
  quota:
    $ref: air-temperature-mcp:air-temperature-mcp-quota-k7m2p:1
