kind: MCPServer
apiVersion: api.ibm.com/v1
metadata:
  name: singapore-air-temperature-mcp-server-k9x2m
  namespace: singapore-air-temperature-mcp
  version: '1'
  tags: []
spec:
  title: Singapore Air Temperature API MCP Server
  protocolVersion: V2025_11_25
  policy-sequence:
    - $ref: singapore-air-temperature-mcp:singapore-air-temperature-mcp-freeflowpolicysequence-k9x2m:1
  capabilities:
    tools:
      - $ref: singapore-air-temperature-mcp:singapore-air-temperature-mcp-tool-k9x2m:1
  quota:
    $ref: singapore-air-temperature-mcp:singapore-air-temperature-mcp-quota-k9x2m:1
